sudo: required
language: go
services:
    - docker
go:
  - 1.6
  - tip
install:
  - go get github.com/Masterminds/glide github.com/onsi/ginkgo/ginkgo github.com/onsi/gomega
script:
  - NUM_NODES=0 make test-all
